//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPiterRetailGroup.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarFillingStation
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public Nullable<int> FuelT92 { get; set; }
        public Nullable<double> Price92 { get; set; }
        public Nullable<int> AmountOfFuel92 { get; set; }
        public Nullable<int> Fuel95 { get; set; }
        public Nullable<double> Price95 { get; set; }
        public Nullable<int> AmountIfFuel95 { get; set; }
        public Nullable<int> Fuel98 { get; set; }
        public Nullable<double> Price98 { get; set; }
        public Nullable<int> AmountIfFuel98 { get; set; }
        public string FuelDis { get; set; }
        public Nullable<decimal> PriceDis { get; set; }
        public Nullable<int> AmountIfFuelDis { get; set; }
    }
}
